### ISSUE TITLE
Nerenderujú sa chránené územia

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/mapsforge-v5#1]
Všimol som si že sa nerenderujú chránené územia.

**Comment by kaylesk** [comment]
No na tie som nejak zabudol :( Ale budú pridané ako samostatná zapínateľná vrstva.

**Comment by kaylesk** [comment]
Chránené územia sú pridané. Objavia sa v nasledujúcom mapovom výstupe (16. 8.) + bude treba mať štýl vyšší ako v1.1.2.
