### ISSUE TITLE
Nerenderuje parky

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/mapsforge-v5#10]
Vyzerá to že sa nerenderujú mestské parky (leisure=park)
![Screenshot_2020-09-05-07-33-22-153_menion android locus pro](https://user-images.githubusercontent.com/19683952/93594708-a375ec80-f9b6-11ea-93bc-52c7b877c5af.jpg)

https://www.freemap.sk/?map=17/48.592590/17.836926&layers=X

**Comment by kaylesk** [comment]
áno, nie. :)
To výstupu sa dané objekty síce generujú, ale štýl nemá definíciu na zobrazenie
