### ISSUE TITLE
vacsie nazvy obci pri vektorovej mape

### ISSUE THREAD

**Issue by PertR** [FreemapSlovakia/mapsforge-v5#12]
Momentalne, ak si oddialim mapu, tak je tam hrozne vela nazvov objektov v priblizne rovnakych velkostiach. Obce su dokonca renderovane so standardnou hrubkou fontu, napr vrchy a ine su s tucnym pismom.

Takze by bolo fajn zvacsit nazvy obci tak 1,5x a dat ich tiez tucnym pismom, pripadne,nejak inak ich zvyraznit.

**Comment by zdila** [comment]
Poziadavky na Locus vektorovu mapu davaj prosim sem: https://github.com/FreemapSlovakia/mapsforge-v5/issues

Tento issue som uz presunul.
