### ISSUE TITLE
Nespravna farba cyklotrasy

### ISSUE THREAD

**Issue by yohny** [FreemapSlovakia/mapsforge-v5#14]
Cyklotrasa Chorvatske rameno, ktora je zelena (a taka sa renderuje aj online na https://www.freemap.sk/?map=19/48.117620/17.107330&layers=X) je v Locuse z nejakeho dovodu cierna
![Screenshot_20210202-181452](https://user-images.githubusercontent.com/5924185/106637263-c0384880-6582-11eb-802f-bc78b066514e.jpg)

**Comment by kaylesk** [comment]
Farba je viac menej správna.
Sú tam totiž dve cyklo.
Jedna je bez farby s názvom "Cyklotrasa R38: Chorvátske rameno" a bezfarebné (alebo nejaká "exotická" farba) sú zobrazené ako čierne. (v mape je  vidieť aj to ref=R38)
https://www.openstreetmap.org/relation/11012943
A potom tam je druhá s názvom "Cyklotrasa Chorvátske rameno", je zelená a je označená proposed (plánovaná) a tie sa nezobrazujú.
https://www.openstreetmap.org/relation/215265

Takže asi by bolo dobre prezistiť, či aktuálne zaznamenaný stav v OSM je správny. Sú si veľmi podobné, i keď iný operator majú.

**Comment by yohny** [comment]
to 'proposed' nie je spravne, cyklotrasa je uz realne existujuca dost dlho (sam som nou par krat siel) takze som ten tag odstranil
otazka ostava preco tam su tie relacie 2 a ako bude mapa vyzerat teraz ked su tam obe

**Comment by kaylesk** [comment]
Netuším prečo sú dve, ale podľa operator (jedna Bratislava a druhá STaRZ) predpokladám, že to bude asi jedna. Len jedna relácia je staršia a druhá novšia. Pričom staršia je tá zelená a asi rok dozadu jej niekto dal proposed.
Farby by mali byť obe.

**Comment by yohny** [comment]
uz to vyzera fajn, zatvaram
