### ISSUE TITLE
Nevykreslena cyklotrasa

### ISSUE THREAD

**Issue by yohny** [FreemapSlovakia/mapsforge-v5#17]
Cyklotrasa https://www.openstreetmap.org/way/544336421#map=14/48.9568/21.3173 nema vykreslene cyklotrasove bodky. Nakolko nema uvedenu farbu tak by asi mali byt cierne ako ine cyklotrasy bez farby. Je mozne ze sa hghway=cycleway vobec nerenderuje ako cyklotrasa a renderuju sa len relacie s route=bicycle? Ak ano tak by podla mna davalo zmysel aby sa renderovali oba varianty.

**Comment by kaylesk** [comment]
Daná cesta je označená len ako highway=cycleway a nie je v žiadnej cyklo relácií. Preto tam žiadne bodky nie sú, ani čierne.
Ale ako pozerám, grafická reprezentácia pre cycleway bude musieť byť zmenená, lebo takto "voľne v prírode" to pri menšom z navodzuje dojem potoka.

**Comment by yohny** [comment]
no prave, nemohli/nemali by sa aj highway=cycleway renderovat rovnako ako cyklotrasy vyrobene relaciami? pretoze davat na highway=cycleway este relaciu ktora povie ze ide o cyklotrasu mi pride zbytocne 😄

**Comment by kaylesk** [comment]
Popravde, nie som moc naklonený nápadu označovať všetky "nereláciové" cycleway.

**Comment by yohny** [comment]
ako sa potom daju identifikovat dedikovane cyklotrasy (highway=cycleway) v takejto outoorovej (=turisticko-cyklo-lyziarskej) mape? ja som cylkotrasove bodky povazoval za indikator cyklotras (a predpokladam ze nie som sam), je to inak?

**Comment by kaylesk** [comment]
Bodky sú zamýšľané len na značené (i keď nie všetky zobrazené budú aj v reálne označené, ale to je iná debata) cyklo a MTB (a MTB má kúsok iné značennie)
ALE už som kedysi uvažoval označovať aj cycleway. Takže cycleway=lane a highway=cycleway nejak (síce ešte úplne neviem ako) označím, pokiaľ tam nie je nejaká značená cyklo trasa.

**Comment by kaylesk** [comment]
Asi budú magenta bodky.

**Comment by kaylesk** [comment]
Ešte to ladím, takže určite sa vzhľad ešte zmení.
![Screenshot_20210427-114041](https://user-images.githubusercontent.com/8353866/116221025-832cbe00-a74d-11eb-9239-6533646040f3.jpg)

**Comment by kaylesk** [comment]
Rôzna cyklo infraštuktúra (cycleway, cyclelane, bicycle=designated, ...) ktorá nie je inak značená (napr. nie je tam farebná cyklo trasa) sa zobrazuje ako purpurové bodky (dve blízko pri sebe, potom výraznejšia medzera, viď obrázok) Aktuálne je tam chyba, zobrazujú sa vždy, nasledujúci update štýlu to opraví a bude sa zobrazovať len keď bude zapnutá cyklo vrstva.

![Screenshot_20210622-101250](https://user-images.githubusercontent.com/8353866/122890407-ef89ff00-d343-11eb-9fd1-76040e23d0e4.jpg)
