### ISSUE TITLE
Nejaká chyba renderovania tur. značky

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/mapsforge-v5#2]
Na Veľký Rozsutec nerenderuje turistické značky iba malý vrcholoví kúsok tam je (viď príloha)

![Screenshot_2019-08-08-12-07-16-345_menion android locus pro](https://user-images.githubusercontent.com/19683952/62818912-3c98c980-bb4e-11e9-86ae-486b1e433504.png)

https://www.freemap.sk/?map=16/49.232185/19.103851&layers=X

**Comment by kaylesk** [comment]
Sú tam viaceré červené (naša a medzinárodná) a preprocesor vie vyhodiť len jednu pre danú farbu. Tu konkrétne na tento úsek použije značky z tejto relácie
https://www.openstreetmap.org/relation/4673482#map=9/49.2104/19.0896

Ja z osmc:symbol vyťahujem symbol, ale tu je taký neštandardný, ktorý sa nespracuje a tam vôbec nevidí, že tam nejaký červený osmc je.
Pôvodne som zamýšľal zobrazovať značky, ale asi sa nateraz na to vykašlem a hodím len všeobecné farby, nech to nerobí takéto problémy.

**Comment by kaylesk** [comment]
Nie je to vidieť (dáta sú z rovnakého dňa), ale updatol som aj existujúcu mapu. Stačí v addon-e vybrať mapu a ťuknúť na "Preinštaluj".
Zatváram, ak by bolo ešte niečo, stačí sa ozvať.

**Comment by seg-on** [comment]
Tie značky si chcel v kombinácií s farbou ako je teraz alebo len značky? Ako asi tým dokážeš viac povedať (miestne značenie, náučný chodník...) ale zas je to podľa mňa menej prehľadné.
Počkám na najbližší update a vyskúšam aj s tými chránenými územiami

**Comment by kaylesk** [comment]
Kombinácia s farbou. Plán bol pridať samostatnú zapínateľnú vrstvu a ukáže aká značka tam je. (pásova, vrchol, studnička, ...)

**Comment by seg-on** [comment]
Tak to by bolo plus :)
