### ISSUE TITLE
Nevykreslene menovky pre objekty s tourism=yes

### ISSUE THREAD

**Issue by yohny** [FreemapSlovakia/mapsforge-v5#20]
Bolo by super ak by sa v locuse renderovali menovky pre objekty s tourism=yes (podobne ako sa renderuju na webe freemap.sk). Priklad https://www.freemap.sk/?map=18/48.415744/17.240505&layers=X&osm-way=30723227

**Comment by kaylesk** [comment]
Nemal by to byť problém. Pozerám, aktuálne sa tourism=yes nachádza na 35 bodoch a 4 cestách (v rámci SK). Väčšina z nich už bude zobrazená (vodopád, kaštieľ, ...) Ale je tam aj pár, ktoré nie sú a zaslúžili by si byť zobrazené.

**Comment by kaylesk** [comment]
Zobrazujú sa v mape od 25.6.2021 so štýlom aspoň 1.6.2

**Comment by yohny** [comment]
prave som updatol mapu (na v2021.3.24) , temu (na v1.6.2) aj db (na v2021.6.24) a popis na vyssie uvedenom priklade nevidim - je potrebne nieco refreshnut/invalidovat cache?

**Comment by kaylesk** [comment]
Zaujímavé, na PC to zobrazilo, na mobile nie. Skús odstrániť a znova nainštalovať tému. Potom mi to zobrazilo.

**Comment by yohny** [comment]
re reinstalacii temy to uz fici, aj ked az pri znacnom zoome

**Comment by kaylesk** [comment]
Od z16 sa zobrazuje. Váhal som aj medzi z15 a z16. Prerábam zobrazovanie názvov pre rôzne POI (ikona nižší zoom a názov až pri vyššom, aby názvy zbytočne nezaberali miesto), tak znížim aj toto.
