### ISSUE TITLE
Kolajnice sa zobrazuju az od prilis vysokeho zoomu

### ISSUE THREAD

**Issue by yohny** [FreemapSlovakia/mapsforge-v5#22]
Kolajnice https://www.openstreetmap.org/way/395768526, https://www.openstreetmap.org/way/4924525 a pod. sa v Locuse zobrazuju az od vysokkeho zoomu. Netusim ci je to na zaklade usage=branch alebo ineho tagu.
Pri 500m mierke ich stale nie je vidno
![Screenshot_20210904-182439](https://user-images.githubusercontent.com/5924185/132101819-3d0fb1df-25e9-471f-a7b9-1ce7e32cf3cc.jpg)
objavia sa az pri 300m mierke
![Screenshot_20210904-182449](https://user-images.githubusercontent.com/5924185/132101855-39ecc108-ecde-498b-9a48-d465020c2056.jpg)
Bolo by fajn ak by boli viditelne vtedy ked su viditelne aj ostatne kolajnice (alebo mozno o level neskor, ak su menej vyznamne)

**Comment by yohny** [comment]
kludne moze byt aj tak, hlavne nech su viditelne trocha skor

Dňa po 13. 9. 2021, 10:18 Michal ***@***.***> napísal(a):

**Comment by yohny** [comment]
s novou aktualizaciou to uz vyzera fajn 👍

**Comment by kaylesk** [comment]
Zatiaľ žiadna aktualizácia štýlu nebola, ale boli nejaké podozrivé úpravy na tratiach. Asi poopravavali - https://groups.google.com/g/osm_sk/c/qxZQAQouuvY
