### ISSUE TITLE
Chránené územia renderuje s chybami

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/mapsforge-v5#4]
Neviem či je to chyba sem alebo na Locus, ale často sa zle vykresľuje šráfovanie chránených území.
![Screenshot_2019-08-24-17-02-06-420_menion android locus pro](https://user-images.githubusercontent.com/19683952/63670304-a070f280-c7dc-11e9-9eba-2df50d9699cd.png)
![Screenshot_2019-08-24-17-01-43-528_menion android locus pro](https://user-images.githubusercontent.com/19683952/63670308-a23ab600-c7dc-11e9-8562-1c7e07f80b7d.png)
Vyzerá to ako keby Polygóny zle uzatváral, respektíve hranice boli porozdeľované a tým pádom neurčí správe plochu.

**Comment by kaylesk** [comment]
Pomohlo by vedieť aký Zoom je na mape a či je nejaké zväčšenie (iné ako 100%). Lebo mne sa také čosi nepodarilo zreprodukovať v locus-e (verzia 3.39.3 ani 3.39.4) ani v app cruiser (verzia 1.7)
Problém o ktorom viem, pri niektorých Z je kreslené orámovanie chránenej oblasti aj po okraji "tajlu".

**Comment by seg-on** [comment]
No prakticky to robí všade a pri všetkých zoomoch. Zväčšenie mám 100% a zoomujem lupou nie prstami takže po jednotlivých hladinách.
Locus 3.39.4
![Screenshot_2019-08-26-14-50-32-964_menion android locus pro](https://user-images.githubusercontent.com/19683952/63692633-6ae6fc00-c812-11e9-9a00-ff8ee8a9114f.png)
![Screenshot_2019-08-26-14-50-21-929_menion android locus pro](https://user-images.githubusercontent.com/19683952/63692634-6cb0bf80-c812-11e9-9c39-9f981eb25b76.png)
![Screenshot_2019-08-26-14-50-24-908_menion android locus pro](https://user-images.githubusercontent.com/19683952/63692636-6f131980-c812-11e9-9185-d2194c1b99e6.png)
![Screenshot_2019-08-26-14-50-28-742_menion android locus pro](https://user-images.githubusercontent.com/19683952/63692639-720e0a00-c812-11e9-9ffc-bbe043e471e6.png)

**Comment by seg-on** [comment]
už to je ok :)
